import os

KAFKA_BOOTSTRAP=os.getenv("KAFKA_BOOTSTRAP_SERVERS")

RAW_TOPIC=os.getenv("KAFKA_RAW_TOPIC")

CLEAN_TOPIC=os.getenv("KAFKA_CLEAN_TOPIC")

ANALYTICS_TOPIC=os.getenv("KAFKA_ANALYTICS_TOPIC")

ELASTIC_HOST=os.getenv("ELASTIC_HOST")

ELASTIC_INDEX=os.getenv("ELASTIC_INDEX")